### ISSUE TITLE
Driver autobidder

### ISSUE THREAD

**Issue by RuralBrick** [RuralBrick/hagglehaul#22]
## User Story
As a **driver**, I would like **an autobidder** so that **I can better compete with other drivers over winning the trip**.

## Detailed Description
Provide additional details and context.

## Tasks
- [] Create autobidder instance
- [] Set autobidder amount(s)

## Acceptance Criteria
- [ ] Given **[Condition]**, then **[Expected Result]**
- [ ] Given **[Condition]**, then **[Expected Result]**
- [ ] Given **[Condition]**, then **[Expected Result]**
