### ISSUE TITLE
Driver auto-rebidder

### ISSUE THREAD

**Issue by RuralBrick** [RuralBrick/hagglehaul#40]
## User Story
As a **driver**, I would like **an auto-rebidder** so that **I can better stay competitive on a trip**.

## Detailed Description
Provide additional details and context.

## Tasks
- [ ] Create auto-rebidder instance
- [ ] Set auto-rebidder limit(s)

## Acceptance Criteria
- [ ] Given **[Condition]**, then **[Expected Result]**
- [ ] Given **[Condition]**, then **[Expected Result]**
- [ ] Given **[Condition]**, then **[Expected Result]**
